### ISSUE TITLE
Wrap train_test split for multi-view data

### ISSUE THREAD

**Issue by gavinmischler** [mvlearn/mvlearn#116]
## Summary of enhancement
For multi-view data, if a user wants to do a train_test_split, like with sklearn, they would need to write a loop and set the random state each time in order to do that to all the views. It might be helpful to wrap sklearn's train_test_split so it works on multi-view data.

For example...

```mvlearn
from mvlearn.utils import train_test_split
Xs_train, Xs_test, y_train, y_test = train_test_split(Xs, y=y, random_state=None)
```
Or
```mvlearn
from mvlearn.utils import train_test_split
Xs_train, Xs_test = train_test_split(Xs, random_state=None)
```

**Comment by achang63** [comment]
If I'm understanding correctly, I'm pretty sure you could already do this with train_test_split. If Xs is your list of arrays, you would just write:

```mvlearn
splits = train_test_split(*Xs)
```
I suppose unpacking the list "splits" might be annoying since you would have to separate the arrays at even and odd indices yourself. If you think this would still merit a wrapper, I can quickly write up a utility for this.

**Comment by gmischl1** [comment]
Yeah it's not like it's all that hard to implement, but it's not just one simple line, so I thought it would be an easy thing to add that would be useful to some people.
